version: '3'
services:
  app:
    image: veritas-be
    container_name: veritas-be
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/veritas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1313
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - mynetwork

  mariadb:
    container_name: veritas-db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 1313
      MARIADB_DATABASE: veritas
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork: