version: '3'
services:
  veritas-be:
    image: oxingaxin/veritas-be:latest
    container_name: veritas-be
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/veritas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1313
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - mynetwork
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - veritas-be
    networks:
      - mynetwork
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - mynetwork


  mariadb:
    container_name: veritas-db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1313
      MARIADB_DATABASE: veritas
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork: